### ISSUE TITLE
Support PostgreSQL Binding

### ISSUE THREAD

**Issue by Mershab99** [OpenFunction/functions-framework#24]
The postgres binding uses the `exec` and `query` operations, and invokes the binding with the SQL command embedded in the `metadata` field of the `dapr.InvokeBindingRequest`. However the current `ctx.Send` method only fills the `data` field. This is insufficient for the postgres binding.

https://docs.dapr.io/reference/components-reference/supported-bindings/postgresql/

Alternatively exposing the daprClient as part of the `FunctionContext` would allow users to access the underlying dapr client and invoke our own methods beyond the scope of the OF spec.

**Comment by tpiperatgod** [comment]
It's a valid point regarding the PostgreSQL binding requirements. Currently, the ff-python framework already supports exposing the Dapr client to users. If you are interested in having the same functionality in ff-go, we would greatly appreciate your contributions to develop this feature.

**Comment by Mershab99** [comment]
Hi @tpiperatgod, I've gone ahead and created a PR in the ff-go repo (mentioned above). However I am incurring some issues with the function builder. Namely that it does not respect the `replace` directive in the `go.mod` file to my own ff-go implementation, so the builder doesn't see the added method. I've sent you an email about this, but perhaps this is an opportunity for me to enhance the builder documentation if I can learn a bit more about how it works!

**Comment by tpiperatgod** [comment]
Hi @Mershab99 , for information on how to make ff-go builder image, see this [doc](https://github.com/OpenFunction/builder/tree/main/builders/go117). Please feel free to give suggestions to enhance the documentation!

**Comment by Mershab99** [comment]
Closing this issue as https://github.com/OpenFunction/functions-framework-go/pull/78 has been merged which addresses this concern. Thanks all for your help!
