### ISSUE TITLE
Functions-framework needs to support Python

### ISSUE THREAD

**Issue by tpiperatgod** [OpenFunction/functions-framework#5]
According to some statistics, Python and Nodejs are currently the two most popular languages in the serverless framework. This means that if OpenFunction's functions-framework can support these two languages, it will expand the number of potential users.

![](https://imgix.datadoghq.com/img/state-of-serverless/FACT_8.png?ch=Width&fit=max&fm=png&auto=format&lossless=1)
> picture from https://www.datadoghq.com/state-of-serverless/

**Comment by FeynmanZhou** [comment]
Hi @tpiperatgod @linxuyalun , is this issue still active? What's the status of Python and Nodejs support?

**Comment by tpiperatgod** [comment]
@linxuyalun has completed the functions-framework-nodejs for OpenFunction v0.3.1.

We currently have no progress on functions-framework-nodejs (and python) for the higher version of OpenFunction.

**Comment by FeynmanZhou** [comment]
Got it, thanks for @linxuyalun's effort!
Hi @webup @ForeverArt @kehuili , are you intersted in helping our community to implement the Functions-framework-Python and Functions-framework-Nodejs?

**Comment by ForeverArt** [comment]
> Got it, thanks for @linxuyalun's effort! Hi @webup @ForeverArt @kehuili , are you intersted in helping our community to implement the Functions-framework-Python and Functions-framework-Nodejs?

Yes, we will start implementing Functions-framework-Python and Functions-framework-Nodejs for the latest version of  OpenFunction.

/assign @kehuli - Python
/assign @ForeverArt - Nodejs

**Comment by benjaminhuo** [comment]
Nodejs functions framework has been supported.

**Comment by benjaminhuo** [comment]
Close this to track the python functions framework in https://github.com/OpenFunction/functions-framework/issues/18
